# .github/workflows/test.yml
name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version}}
        poetry_version: 1.0.5
        args: install
    - name: Install nox
      run: pip install nox==2019.11.9
    - name: Install dependencies 
      run: poetry install
    - name: Run nox
      run: nox
